version: "3.9"

services:
  node_api:
    container_name: node_api
    build: .
    image: zackolivier/node_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=node_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=node_api
      - POSTGRES_DIALECT=postgres
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - node_db_data:/var/lib/postgresql/data


